account_id = "7f3e801a63603396808afdbc0cdc3c16"
name = "wikijuris"

compatibility_date = "2025-07-01"

[assets]
directory = "public"

[env.dev]
name = "dev"
workers_dev = true
routes = [
  { pattern = "alpha.wikijuris.net", custom_domain = true }
]

[env.wiki]
name = "wiki"
workers_dev = true
routes = [
  { pattern = "wikijuris.net", custom_domain = true },
  { pattern = "beta.wikijuris.net", custom_domain = true }
]
